/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM_Project;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/*
 *
 * @author omerc
 */ class IslemMenusu extends javax.swing.JFrame {
  
    int yetki;


    /**
     * Creates new form IslemMenusu2
     */
    public IslemMenusu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jbtnSifreDegistirme = new javax.swing.JButton();
        jBtnBakiyeGoruntule = new javax.swing.JButton();
        jBtnParaCekme = new javax.swing.JButton();
        jBtnParaYatirma = new javax.swing.JButton();
        jBtnKrediBasvurusu = new javax.swing.JButton();
        jBtnFaturaOdeme = new javax.swing.JButton();
        jBtnKrediKartBasvuru = new javax.swing.JButton();
        jBtnKr = new javax.swing.JButton();
        jBtnParaTransferi = new javax.swing.JButton();
        jBtnKrediBasvurulari = new javax.swing.JButton();
        jBtnKrediKartiBasvurulari = new javax.swing.JButton();
        jBtnGeri = new javax.swing.JButton();
        jBtnKrediKartiLimitBasvurulari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnSifreDegistirme.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnSifreDegistirme.setText("Şifre Değiştirme");
        jbtnSifreDegistirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSifreDegistirmeActionPerformed(evt);
            }
        });

        jBtnBakiyeGoruntule.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnBakiyeGoruntule.setText("Bakiye Sorgulama");
        jBtnBakiyeGoruntule.setAutoscrolls(true);
        jBtnBakiyeGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBakiyeGoruntuleActionPerformed(evt);
            }
        });

        jBtnParaCekme.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnParaCekme.setText("Para Çekme");
        jBtnParaCekme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnParaCekmeActionPerformed(evt);
            }
        });

        jBtnParaYatirma.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnParaYatirma.setText("Para Yatırma");
        jBtnParaYatirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnParaYatirmaActionPerformed(evt);
            }
        });

        jBtnKrediBasvurusu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnKrediBasvurusu.setText("Kredi Başvurusu");
        jBtnKrediBasvurusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKrediBasvurusuActionPerformed(evt);
            }
        });

        jBtnFaturaOdeme.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnFaturaOdeme.setText("Fatura Ödeme");
        jBtnFaturaOdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFaturaOdemeActionPerformed(evt);
            }
        });

        jBtnKrediKartBasvuru.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnKrediKartBasvuru.setText("Kredi Kartı Başvurusu");
        jBtnKrediKartBasvuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKrediKartBasvuruActionPerformed(evt);
            }
        });

        jBtnKr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnKr.setText("K.K.Limit Güncelleme");
        jBtnKr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKrActionPerformed(evt);
            }
        });

        jBtnParaTransferi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnParaTransferi.setText("Para Transferi");
        jBtnParaTransferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnParaTransferiActionPerformed(evt);
            }
        });

        jBtnKrediBasvurulari.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnKrediBasvurulari.setText("Kredi Başvuruları");
        jBtnKrediBasvurulari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKrediBasvurulariActionPerformed(evt);
            }
        });

        jBtnKrediKartiBasvurulari.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnKrediKartiBasvurulari.setText("Kredi Kartı Başvuruları");
        jBtnKrediKartiBasvurulari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKrediKartiBasvurulariActionPerformed(evt);
            }
        });

        jBtnGeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnGeri.setText("Geri");
        jBtnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGeriActionPerformed(evt);
            }
        });

        jBtnKrediKartiLimitBasvurulari.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnKrediKartiLimitBasvurulari.setText("Kredi Kartı Limit Talepleri");
        jBtnKrediKartiLimitBasvurulari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKrediKartiLimitBasvurulariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnKr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnParaTransferi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSifreDegistirme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnFaturaOdeme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnBakiyeGoruntule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnKrediBasvurulari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnParaCekme, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnKrediKartBasvuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnKrediKartiBasvurulari, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnKrediBasvurusu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnKrediKartiLimitBasvurulari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnGeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnParaYatirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnParaYatirma, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jBtnParaCekme, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnSifreDegistirme, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jBtnBakiyeGoruntule, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnParaTransferi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jBtnFaturaOdeme, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnKrediBasvurusu, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jBtnKrediKartBasvuru, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnKr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnKrediBasvurulari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnKrediKartiBasvurulari, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnKrediKartiLimitBasvurulari, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jBtnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSifreDegistirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSifreDegistirmeActionPerformed
            this.toBack();
            SifreDegistirme sifreDegistirme = new SifreDegistirme();
            sifreDegistirme.setVisible(true);
            sifreDegistirme.toFront();
    }//GEN-LAST:event_jbtnSifreDegistirmeActionPerformed

    private void jBtnKrediBasvurusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKrediBasvurusuActionPerformed
        KrediBasvurusu Info = new KrediBasvurusu();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnKrediBasvurusuActionPerformed

    private void jBtnBakiyeGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBakiyeGoruntuleActionPerformed
           BakiyeSorgulama Info = new BakiyeSorgulama();
           Info.setVisible(true);
    }//GEN-LAST:event_jBtnBakiyeGoruntuleActionPerformed

    private void jBtnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGeriActionPerformed
            this.toBack();
            setVisible(false);
            new Login().toFront();
            new Login().setState(java.awt.Frame.NORMAL);
            
            
            
    }//GEN-LAST:event_jBtnGeriActionPerformed

    private void jBtnParaCekmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnParaCekmeActionPerformed
        ParaCekme Info = new ParaCekme();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnParaCekmeActionPerformed

    private void jBtnParaYatirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnParaYatirmaActionPerformed
        ParaYatirma Info = new ParaYatirma();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnParaYatirmaActionPerformed

    private void jBtnParaTransferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnParaTransferiActionPerformed
        ParaTransferi Info = new ParaTransferi();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnParaTransferiActionPerformed

    private void jBtnFaturaOdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFaturaOdemeActionPerformed
        FaturaOdeme Info = new FaturaOdeme();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnFaturaOdemeActionPerformed

    private void jBtnKrediKartBasvuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKrediKartBasvuruActionPerformed
        KrediKartiBasvurusu Info = new KrediKartiBasvurusu();
        Info.setVisible(true);
        
    }//GEN-LAST:event_jBtnKrediKartBasvuruActionPerformed

    private void jBtnKrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKrActionPerformed
                Kullanıcı k3 = new Musteri();
        DBConnection db = new DBConnection();
    
        try{
            db.DBBaglanti();
        }
        catch (SQLException ex) {
            Logger.getLogger(IslemMenusu.class.getName()).log(Level.SEVERE, null,ex);
        }
         
        yetki = k3.kontrolyetki(k3.user);
        if(yetki==3){
            JOptionPane.showMessageDialog(null,"Yetkiniz yok","Hata",JOptionPane.ERROR_MESSAGE);
        }
        else{
        KrediKartiLimitGuncelleme Info = new KrediKartiLimitGuncelleme();
        Info.setVisible(true);
        }
    }//GEN-LAST:event_jBtnKrActionPerformed

    private void jBtnKrediKartiLimitBasvurulariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKrediKartiLimitBasvurulariActionPerformed
        Kullanıcı k3 = new Musteri();
        DBConnection db = new DBConnection();
        
        try{
            db.DBBaglanti();
        }
        catch (SQLException ex) {
            Logger.getLogger(IslemMenusu.class.getName()).log(Level.SEVERE, null,ex);
        }
     
     
        
        yetki = k3.kontrolyetki(k3.user);
        if(yetki==3){
            JOptionPane.showMessageDialog(null,"Yetkiniz yok","Hata",JOptionPane.ERROR_MESSAGE);
        }
        else{
        KrediKartiLimitTalepleri Info = new KrediKartiLimitTalepleri();
        Info.setVisible(true);
        }
    }//GEN-LAST:event_jBtnKrediKartiLimitBasvurulariActionPerformed

    private void jBtnKrediBasvurulariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKrediBasvurulariActionPerformed
                Kullanıcı k3 = new Musteri();
        DBConnection db = new DBConnection();
        
        try{
            db.DBBaglanti();
        }
        catch (SQLException ex) {
            Logger.getLogger(IslemMenusu.class.getName()).log(Level.SEVERE, null,ex);
        }
    
        
        yetki = k3.kontrolyetki(k3.user);
        if(yetki == 2){
            JOptionPane.showMessageDialog(null,"Yetkiniz yok","Hata",JOptionPane.ERROR_MESSAGE);
            
        }
        else if(yetki==3){
            JOptionPane.showMessageDialog(null,"Yetkiniz yok","Hata",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            KrediBasvurulari Info = new KrediBasvurulari();
            Info.setVisible(true);
        }
    }//GEN-LAST:event_jBtnKrediBasvurulariActionPerformed

    private void jBtnKrediKartiBasvurulariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKrediKartiBasvurulariActionPerformed
                Kullanıcı k3 = new Musteri();
        DBConnection db = new DBConnection();
        
        try{
            db.DBBaglanti();
        }
        catch (SQLException ex) {
            Logger.getLogger(IslemMenusu.class.getName()).log(Level.SEVERE, null,ex);
        }
        
        k3.user = k3.user_();
        
        yetki = k3.kontrolyetki(k3.user);
        if(yetki==3){
            JOptionPane.showMessageDialog(null,"Yetkiniz yok","Hata",JOptionPane.ERROR_MESSAGE);
        }
        else{
        KrediKartiBasvurulari Info = new KrediKartiBasvurulari();
        Info.setVisible(true);
        }
    }//GEN-LAST:event_jBtnKrediKartiBasvurulariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IslemMenusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IslemMenusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IslemMenusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IslemMenusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IslemMenusu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBakiyeGoruntule;
    private javax.swing.JButton jBtnFaturaOdeme;
    private javax.swing.JButton jBtnGeri;
    private javax.swing.JButton jBtnKr;
    private javax.swing.JButton jBtnKrediBasvurulari;
    private javax.swing.JButton jBtnKrediBasvurusu;
    private javax.swing.JButton jBtnKrediKartBasvuru;
    private javax.swing.JButton jBtnKrediKartiBasvurulari;
    private javax.swing.JButton jBtnKrediKartiLimitBasvurulari;
    private javax.swing.JButton jBtnParaCekme;
    private javax.swing.JButton jBtnParaTransferi;
    private javax.swing.JButton jBtnParaYatirma;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbtnSifreDegistirme;
    // End of variables declaration//GEN-END:variables
}
