/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM_Project;


import java.sql.*;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omerc
 */

public class KrediKartiBasvurulari extends javax.swing.JFrame {
 
    
    
    
   
    public KrediKartiBasvurulari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGeri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnOnaylaKrediKart = new javax.swing.JButton();
        jBtnReddet = new javax.swing.JButton();
        jBtnGoruntule = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnGeri.setText("Geri");
        jBtnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGeriActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("İşlem Yapılacak Kişinin Adı:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jBtnOnaylaKrediKart.setText("Onayla");
        jBtnOnaylaKrediKart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOnaylaKrediKartActionPerformed(evt);
            }
        });

        jBtnReddet.setText("Reddet");
        jBtnReddet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReddetActionPerformed(evt);
            }
        });

        jBtnGoruntule.setText("Görüntüle");
        jBtnGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGoruntuleActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HESAPID", "MAAS", "EVSAHIBIMI", "LIMIT"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnOnaylaKrediKart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jBtnReddet, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jBtnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jBtnGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtnGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOnaylaKrediKart, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReddet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGeriActionPerformed
        this.toBack();
            setVisible(false);
            new IslemMenusu().toFront();
            new IslemMenusu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jBtnGeriActionPerformed

    private void jBtnGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGoruntuleActionPerformed
 try {
           
     try (Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/bank","omer","omer")) {
         Statement st = conn.createStatement();
         String sql = "SELECT * FROM OMER.KREDIKARTITALEPLERI";
         ResultSet rs = st.executeQuery(sql);
         
         
         while(rs.next()){
             double limit =rs.getDouble(4);
             String KREDIMIKTARI =String.valueOf(limit);
             boolean EVKIRAVEYADEGIL = rs.getBoolean(3);
             double  maas=rs.getDouble(2);
             String MAAS = String.valueOf(maas);
             String HESAPID = rs.getString(1);
             String str=String.valueOf(EVKIRAVEYADEGIL);
             String tbData[] = {HESAPID,MAAS,str,KREDIMIKTARI};
             DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
             tblModel.addRow(tbData);
         }
     }
           
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }   
    }//GEN-LAST:event_jBtnGoruntuleActionPerformed

    private void jBtnReddetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReddetActionPerformed
        String id = jTextField1.getText();
        Kullanıcı k = new Kullanıcı();
        try {
            k.KKBasvuruReddetme(id);
        } catch (SQLException ex) {
            Logger.getLogger(KrediKartiLimitTalepleri.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1.setText(null);
        JOptionPane.showMessageDialog(null,"Talep Reddedildi","Kredi Kart Başvuruları",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jBtnReddetActionPerformed

    private void jBtnOnaylaKrediKartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOnaylaKrediKartActionPerformed
        String id = jTextField1.getText();
        Kullanıcı k = new Kullanıcı();
         try {
            k.KKBasvuruOnaylama(id);
        } catch (SQLException ex) {
            Logger.getLogger(KrediKartiLimitTalepleri.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1.setText(null);
        JOptionPane.showMessageDialog(null,"Talep Kabul Edildi","Kredi Kart Başvuruları",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBtnOnaylaKrediKartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrediKartiBasvurulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrediKartiBasvurulari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGeri;
    private javax.swing.JButton jBtnGoruntule;
    private javax.swing.JButton jBtnOnaylaKrediKart;
    private javax.swing.JButton jBtnReddet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
